apiVersion: v1
kind: Service
metadata:
  name: ilb-mongodb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: ilb-mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
  - port: 80
    targetPort: 27017
    protocol: TCP